[project]
name = "demo-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.0.3",
    "langgraph>=1.0.2",
    "pandas>=2.3.3",
]
